In [1]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
data=pd.read_csv("missing_data1.csv")
data

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7        450  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
data['Calories'].fillna(data['Calories'].mean(),inplace=True)
data

C:\Users\HP\AppData\Local\Temp\ipykernel_9228\917119035.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Calories'].fillna(data['Calories'].mean(),inplace=True)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       120    479.00
2         60  '2020/12/03'    103       120    340.00
3         45  '2020/12/04'    109       120    282.40
4         45  '2020/12/05'    117       120    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       120    374.00
7        450  '2020/12/08'    104       120    253.30
8         30  '2020/12/09'    109       120    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       120    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       120    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       120    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       120    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       120    304.68
29        60  '2020/12/29'    100       120    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [6]:
data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64